bsite/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from home.views import home
from pages.views import page
urlpatterns = [
    path('admin/', admin.site.urls),
    path('comments/', include('django_comments_xtd.urls')),
    path("", home, name="home"),
    path("<path:url>", page, name="page")
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

home/urls.py
from .views import home
from django.urls import path, include
urlpatterns = [
  path("", home),
]

pages/urls.py
from .views import page
from django.urls import path, re_path
urlpatterns = [
  re_path(r"^(?P<path>.*)$", page, name="page"),
]

home/models.py
from django.db import models

# Create your models here.

pages/models.py
from django.db import models
from mptt.models import MPTTModel, TreeForeignKey


class Page(MPTTModel):
    name = models.CharField(max_length=50)
    parent = TreeForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='children')
    slug = models.SlugField(max_length=50)
    url = models.CharField(max_length=500, default="/", unique=True)

    class Meta:
        ordering = ["pk",]
    class MPTTMeta:
        order_insertion_by = ['name']

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return self.url


class Verse(models.Model):
    """Стихи."""
    page = models.ForeignKey(Page, on_delete=models.CASCADE)
    verse_number = models.IntegerField()
    text = models.TextField()

    def __str__(self):
        return f'{self.page.name}:{self.verse_number} {self.page.title} '

    class Meta:
        ordering = ["pk",]

home/views.py
from django.shortcuts import render
from pages.models import Page
from .constants import HOME_PATH


def home(request):
    cnxt: dict = {}
    home_page = Page.objects.get(url=HOME_PATH)
    cnxt["home_page"] = home_page
    cnxt["subpages"] = Page.objects.filter(parent=home_page).order_by('pk')
    return render(request, "home/index.html", cnxt)

pages/views.py
from django.shortcuts import render
from .models import Page

def page(request, url):
    cnxt: dict = {}
    page = Page.objects.get(url=request.path)
    cnxt["page"] = page
    cnxt["subpages"] = Page.objects.filter(parent=page).order_by('pk')
    return render(request, 'pages/index.html', cnxt)

home/templates/base.html
<!DOCTYPE html>{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="icon" href="{% static 'favicon/favicon.ico' %}" type="image/x-icon">
  </head>
  <body>
  <header>
  </header>
  {% block content %}{% endblock %}
  <footer>
  </footer>
  </body>
</html>

home/templates/home/index.html
{% extends "base.html" %}
{% block content %}
<main>
    <h1>Books</h1>
    <ul>
        {% for page in subpages %}
        <li><a href="{{ page.url }}">{{ page.name }}</a></li>
        {% endfor %}
    </ul>
</main>
{% endblock %}

pages/templates/pages/index.html
{% extends "base.html" %}{% load comments %}
{% block content %}
<main>
    <h1>{{ page.name }}</h1>
    {% if subpages %}
    <ul>
        {% for page in subpages %}
        <li><a href="{{ page.url }}">{{ page.name }}</a></li>
        {% endfor %}
    </ul>
    {% endif %}
    {% if page.verse_set %}
    <ul class="verse">
        {% for verse in page.verse_set.all %}
        <li id="{{ page.name }}:{{ verse.verse_number }}"><b>{{ page.name }}:{{ verse.verse_number }}</b> {{ verse.text }}</a></li>
        {% endfor %}
    </ul>
    {% endif %}
    <hr noshade class="before_comments"/>
    {% if comment_count %}
    <div class="comments">
        {% render_comment_list for page %}
    </div>
    {% endif %}
    <div class="card card-block mb-5">
        <div class="card-body">
            <h4 class="card-title text-center pb-3">Post your comment</h4>
            {% render_comment_form for page %}
        </div>
    </div>
</main>
{% endblock %}